#!/usr/bin/env python3

import os
import subprocess
from tkinter import Tk, ttk, filedialog


def _prime_app():
    import friction  # noqa


class FrictionUI(object):
    def __init__(self):
        self.server_process = None
        self.library_path = None

        self.window = Tk()

        self.window.title('friction')
        self.window.createcommand('exit', self.handle_exit)

        frame = ttk.Frame(self.window)
        ttk.Button(
            frame, text='choose library', command=self.choose_library,
        ).pack()
        self.library_path_label = ttk.Label(frame)
        self.run_toggle = ttk.Button(
            frame, text='start', command=self.toggle_running
        )
        self.run_toggle.pack()

        frame.pack()
        self.choose_library()
        self.window.mainloop()

    def choose_library(self):
        while not self.library_path:
            self.library_path = filedialog.askdirectory()

        self.library_path_label.config(text=self.library_path)
        self.library_path_label.pack()

    def close_server(self):
        self.server_process.terminate()
        self.server_process.wait()
        self.server_process = None

    def toggle_running(self):
        self.run_toggle.state(['disabled'])

        if self.server_process is None:
            self.run_toggle.config(text='stop')
            self.server_process = subprocess.Popen(
                [os.path.join(os.path.dirname(__file__), 'friction')],
                cwd=self.library_path,
            )
        else:
            self.run_toggle.config(text='start')
            self.close_server()

        self.run_toggle.state(['!disabled'])

    def handle_exit(self):
        if self.server_process is not None:
            self.close_server()
        self.window.destroy()

ui = FrictionUI()
